site:
  theme: Copper
  baseUrl: 'https://copper-leaf.github.io/thistle/'
  about:
    siteName: Thistle
    siteDescription: Kotlin Multiplatform String markup and formatting utility

theme:
  social:
    other:
      - link: 'https://copper-leaf.github.io/thistle'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/copper-leaf/thistle'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'wikiSections'
    - type: 'page'
      itemId: 'Changelog'
  sidebarBackground: 'primary'
  sidebarBackgroundType: GRADIENT
  colors:
    green: '#D8BFD8'
  palette:
    primary: 'PURPLE'
    link: 'PURPLE'
    linkVisited: 'BLUE'

changelog:
  adapter:
    type: "file"
    baseDir: "./../../../../"

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'copper-leaf/thistle'
        username: 'cjbrooks12'
        commitish: 'master'
      - type: githubPages
        repo: 'copper-leaf/thistle'
        username: 'cjbrooks12'
  generators:
    disabled:
      - 'kotlindoc'
      - 'indices'

wiki:
  wikiPages:
    layout: wiki
    menu:
      - type: wiki

allPages:
  layoutConfig:
    wrapPageInBox: true
    wrapTitleInBox: true
    includeTitle: false
    includeBreadcrumbs: true
    pageContentsMenu:
      - type: 'separator'
        title: 'In This Page'
      - type: 'pageIds'
        structure: nested
        maxLevel: 2
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy

snippets:
  sections:
    - tags: ['embedded_snippets']
      adapter:
        type: 'embedded'
        recursive: true
        baseDirs:
          - './../../../../thistle-core/'

