# On pushes to master, run tests on all supported platforms. If all tests pass, then publish release artifacts and
# update Orchid documentation site.

name: 'Push to `master` (Create Release)'

on:
  push:
    branches: ['master']

jobs:
  buildCachesOnAll:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    name: 'Build on ${{ matrix.os }} JDK 8'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 8'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'adopt'
          java-version: 8
      - name: 'Cache Gradle packages'
        uses: 'actions/cache@v1'
        with:
          path: '~/.gradle/caches'
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: '${{ runner.os }}-gradle'
      - name: 'Assemble with Gradle'
        run: './gradlew assemble --no-daemon --stacktrace -Prelease -PorchidEnvironment=prod'
  testOnAll:
    needs: ['buildCachesOnAll']
    strategy:
      matrix:
        java: [8, 9, 10, 11, 12, 13, 14, 15, 16]
        os: ['ubuntu-latest', 'macos-latest']
    name: 'Test on ${{ matrix.os }} JDK ${{ matrix.java }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'adopt'
          java-version: '${{ matrix.java }}'
      - name: 'Cache Gradle packages'
        uses: 'actions/cache@v1'
        with:
          path: '~/.gradle/caches'
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: '${{ runner.os }}-gradle'
      - name: 'Run checks with Gradle'
        run: './gradlew check --no-daemon --stacktrace -Prelease -PorchidEnvironment=prod'
  publishOnMacOs:
    runs-on: 'macos-latest'
    needs: ['testOnAll']
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 1.8'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'adopt'
          java-version: 8
      - name: 'Cache Gradle packages'
        uses: 'actions/cache@v1'
        with:
          path: '~/.gradle/caches'
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: '${{ runner.os }}-gradle'
      - name: 'Publish to GitHub Packages'
        run: './gradlew publish --no-daemon --stacktrace -Prelease -PorchidEnvironment=prod'
        env:
          GITHUB_ACTOR: '${{ github.actor }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          OSSRH_USERNAME: '${{ secrets.OSSRH_USERNAME }}'
          OSSRH_PASSWORD: '${{ secrets.OSSRH_PASSWORD }}'
          SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
          SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
          SIGNING_PASSWORD: '${{ secrets.SIGNING_PASSWORD }}'

