# On pushes to `docs` branch, build and publish the Orchid documentation site

name: 'Push to `docs` (Update Docs Site)'

on:
  push:
    branches: ['docs']

jobs:
  publishOnMacOs:
    runs-on: 'macos-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 1.8'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'adopt'
          java-version: 8
      - name: 'Cache Gradle packages'
        uses: 'actions/cache@v1'
        with:
          path: '~/.gradle/caches'
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: '${{ runner.os }}-gradle'
      - name: 'Publish Orchid site'
        run: './gradlew assemble :docs:publish --no-daemon --stacktrace'
        env:
          GITHUB_ACTOR: '${{ github.actor }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
